const {
  BACKEND_HTTP_URL,
  WS_URL: BACKEND_WS_URL,
  USER_CONCURRENCY,
  MONGODB_URI,
  STRIPE_SECRET_KEY,
  STRIPE_PRICE_ID,
  STRIPE_WEBHOOK_SECRET,
  PORT,
  DEV,
  SMTP_URL,
  SUPPORT_EMAIL,
  NODE_ENV,
} = require('../../config/env');

module.exports = {
  BACKEND_HTTP_URL,
  BACKEND_WS_URL,
  USER_CONCURRENCY,
  MONGODB_URI,
  STRIPE_SECRET_KEY,
  STRIPE_PRICE_ID,
  STRIPE_WEBHOOK_SECRET,
  PORT,
  DEV,
  SMTP_URL,
  SUPPORT_EMAIL,
  NODE_ENV,
};
